import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { readFile, rm, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PORT = 3130;
const BASE = `http://127.0.0.1:${PORT}`;
const results=[];
const sessions=[];
let server=null;
let currentSession=0;

function log(...a){ console.log(...a); }
async function check(name, fn, {critical=false}={}){
  const started=Date.now();
  try { await fn(); results.push({session:currentSession,name,ok:true,ms:Date.now()-started}); log('PASS',`S${currentSession}`,name); return true; }
  catch(e){ results.push({session:currentSession,name,ok:false,ms:Date.now()-started,detail:e?.stack||e?.message||String(e)}); log('FAIL',`S${currentSession}`,name,'-',e?.message||e); if(critical) throw e; return false; }
}
async function group(n,title,fn){ currentSession=n; const before=results.length; log(`\n=== SESSÃO ${n}: ${title} ===`); await fn(); const slice=results.slice(before); sessions.push({session:n,title,passed:slice.filter(x=>x.ok).length,total:slice.length,failed:slice.filter(x=>!x.ok).map(x=>x.name)}); }
function client(label){ let cookie=''; return {label,get cookie(){return cookie;},async req(p,{method='GET',body,expected,headers={}}={}){ const opts={method,headers:{...headers}}; if(cookie) opts.headers.Cookie=cookie; if(body!==undefined){ if(Buffer.isBuffer(body)||body instanceof Uint8Array){ opts.body=body; } else { opts.headers['Content-Type']='application/json'; opts.body=JSON.stringify(body); } } const r=await fetch(BASE+p,opts); const sc=r.headers.get('set-cookie'); if(sc) cookie=sc.split(';')[0]; let data; const ct=r.headers.get('content-type')||''; if(ct.includes('application/json')) data=await r.json().catch(()=>({})); else data=await r.text(); if(expected!==undefined) assert.equal(r.status,expected,`${label} ${method} ${p}: ${r.status} ${JSON.stringify(data)}`); return {status:r.status,data,headers:r.headers}; },async upload(filePath,kind,mime){ const bytes=await readFile(filePath); return this.req('/api/upload',{method:'POST',body:bytes,expected:201,headers:{'Content-Type':mime,'X-Upload-Kind':kind,'X-File-Name':path.basename(filePath)}}); }} }
async function startServer(){ server=spawn(process.execPath,['server/server.js'],{cwd:ROOT,env:{...process.env,PORT:String(PORT),HOST:'127.0.0.1'},stdio:['ignore','pipe','pipe']}); server.stdout.on('data',d=>process.stdout.write('[server] '+d)); server.stderr.on('data',d=>process.stderr.write('[server-err] '+d)); const deadline=Date.now()+10000; while(Date.now()<deadline){ try{ const r=await fetch(BASE+'/api/system/network'); if(r.ok) return; }catch{} await new Promise(r=>setTimeout(r,100)); } throw new Error('Servidor não iniciou'); }
async function stopServer(){ if(!server) return; server.kill('SIGTERM'); await Promise.race([new Promise(r=>server.once('exit',r)),new Promise(r=>setTimeout(r,2000))]); if(server.exitCode===null) server.kill('SIGKILL'); server=null; }

await rm(path.join(ROOT,'data','elysium.db'),{force:true});
await rm(path.join(ROOT,'data','elysium.db-shm'),{force:true});
await rm(path.join(ROOT,'data','elysium.db-wal'),{force:true});
await rm(path.join(ROOT,'public','uploads'),{recursive:true,force:true});
await mkdir(path.join(ROOT,'public','uploads'),{recursive:true});
await startServer();

const gm=client('GM'), co=client('CO'), p1=client('P1'), p2=client('P2'), p3=client('P3'), spec=client('SPEC'), outsider=client('OUT');
let U={}, cid, chars={}, uploads={}, scene={}, obj={}, ids={};

await group(1,'Prólogo, contas, Crônica, convites e fichas',async()=>{
  await check('Rede/sistema responde',async()=>{const r=await gm.req('/api/system/network',{expected:200});assert.equal(r.data.app,'elysium')},{critical:true});
  await check('Cadastro do primeiro usuário vira Admin/Dono',async()=>{const r=await gm.req('/api/register',{method:'POST',body:{name:'Mestre',email:'gm@campanha.test',password:'senha1234'},expected:201});U.gm=r.data.user;assert.equal(r.data.user.isAdmin,true)},{critical:true});
  for(const [key,cl,name,email] of [['co',co,'Co-Mestre','co@campanha.test'],['p1',p1,'Alice','alice@campanha.test'],['p2',p2,'Bruno','bruno@campanha.test'],['p3',p3,'Carla','carla@campanha.test'],['spec',spec,'Espectador','spec@campanha.test'],['out',outsider,'Forasteiro','out@campanha.test']]){
    await check(`Cadastro ${name}`,async()=>{const r=await cl.req('/api/register',{method:'POST',body:{name,email,password:'senha1234'},expected:201});U[key]=r.data.user;assert.equal(r.data.user.isAdmin,false)},{critical:true});
  }
  await check('Cadastro duplicado é rejeitado',async()=>await outsider.req('/api/register',{method:'POST',body:{name:'Outro',email:'alice@campanha.test',password:'senha1234'},expected:409}));
  await check('Upload de banner PNG real',async()=>{uploads.banner=(await gm.upload(path.join(ROOT,'tests','fixtures','scene.png'),'image','image/png')).data.url;assert.match(uploads.banner,/^\/uploads\//)});
  await check('Upload rejeita MIME incompatível',async()=>{const b=await readFile(path.join(ROOT,'tests','fixtures','scene.png'));await gm.req('/api/upload',{method:'POST',body:b,expected:415,headers:{'Content-Type':'text/plain','X-Upload-Kind':'image','X-File-Name':'x.txt'}})});
  await check('Crônica criada',async()=>{const r=await gm.req('/api/chronicles',{method:'POST',body:{name:'Sangue sobre Vitória',subtitle:'Campanha de 10 sessões',city:'Vitória',period:'2026',style:'Intriga urbana',bannerUrl:uploads.banner,description:'Teste de campanha extensa'},expected:201});cid=r.data.chronicle.id},{critical:true});
  await check('Edição de metadados da Crônica',async()=>{await gm.req(`/api/chronicles/${cid}`,{method:'PATCH',body:{subtitle:'Crônica completa',status:'active'},expected:200});const r=await gm.req(`/api/chronicles/${cid}`,{expected:200});assert.equal(r.data.chronicle.subtitle,'Crônica completa')});
  for(const [key,cl,role] of [['co',co,'co-master'],['p1',p1,'player'],['p2',p2,'player'],['p3',p3,'player'],['spec',spec,'spectator']]){
    await check(`Convite ${role} e entrada de ${key}`,async()=>{const inv=await gm.req(`/api/chronicles/${cid}/invitations`,{method:'POST',body:{role},expected:201});await cl.req('/api/invitations/join',{method:'POST',body:{code:inv.data.code},expected:200})},{critical:true});
  }
  await check('Convite inválido é rejeitado',async()=>await outsider.req('/api/invitations/join',{method:'POST',body:{code:'INVALIDO'},expected:404}));
  await check('Forasteiro não acessa Crônica',async()=>await outsider.req(`/api/chronicles/${cid}`,{expected:403}));
  await check('Membros e papéis corretos',async()=>{const r=await gm.req(`/api/chronicles/${cid}/members`,{expected:200});assert.equal(r.data.members.length,6);assert.equal(r.data.members.find(x=>x.id===U.co.id).role,'co-master');assert.equal(r.data.members.find(x=>x.id===U.spec.id).role,'spectator')});
  await check('Presença heartbeat de todos',async()=>{for(const cl of [gm,co,p1,p2,p3,spec]) await cl.req(`/api/chronicles/${cid}/presence`,{method:'POST',body:{},expected:200});const r=await gm.req(`/api/chronicles/${cid}/members`,{expected:200});assert.ok(r.data.members.every(m=>m.is_online===1))});
  for(const [key,cl,name,concept,clan] of [['p1',p1,'Helena Prado','Investigadora','Toreador'],['p2',p2,'Davi Moraes','Hacker','Nosferatu'],['p3',p3,'Lívia Reis','Executiva','Ventrue']]){
    await check(`Criação da ficha ${name}`,async()=>{const r=await cl.req(`/api/chronicles/${cid}/characters`,{method:'POST',body:{name,concept,clan,predator:'Sereia'},expected:201});chars[key]=r.data.characterId},{critical:true});
  }
  await check('Espectador não cria ficha',async()=>await spec.req(`/api/chronicles/${cid}/characters`,{method:'POST',body:{name:'Espectador PC'},expected:403}));
  await check('Upload e edição completa de avatar/ficha',async()=>{uploads.avatar=(await p1.upload(path.join(ROOT,'tests','fixtures','scene.png'),'image','image/png')).data.url;await p1.req(`/api/characters/${chars.p1}`,{method:'PATCH',body:{avatarUrl:uploads.avatar,story:'História extensa',attributes:{forca:2,destreza:3,vigor:2,carisma:4},skills:{investigacao:4,persuasao:3},specialties:['Cenas de crime'],disciplines:[{name:'Presença',level:2}],advantages:['Recursos'],flaws:['Inimigo'],convictions:['Não ferir inocentes'],touchstones:['Irmã'],hunger:2,humanity:7,stains:1,healthCurrent:3,healthMax:5,willpowerCurrent:4,willpowerMax:5,bloodPotency:2,resonance:'Fleumática'},expected:200});const r=await p1.req(`/api/characters/${chars.p1}`,{expected:200});assert.equal(r.data.character.attributes.destreza,3);assert.equal(r.data.character.skills.investigacao,4);assert.equal(r.data.character.avatar_url,uploads.avatar)});
  await check('Jogador não edita ficha alheia',async()=>await p2.req(`/api/characters/${chars.p1}`,{method:'PATCH',body:{hunger:5},expected:403}));
  await check('Mestre concede XP',async()=>{await gm.req(`/api/characters/${chars.p1}/xp`,{method:'POST',body:{amount:3,reason:'Prólogo'},expected:200});const r=await p1.req(`/api/characters/${chars.p1}`,{expected:200});assert.equal(r.data.character.xp_available,3)});
  await check('Jogador não concede XP',async()=>await p1.req(`/api/characters/${chars.p1}/xp`,{method:'POST',body:{amount:10},expected:403}));
});

await group(2,'Investigação: cenas, diretórios, notas, diário e comunicação',async()=>{
  await check('Uploads de mapa, foreground e áudio reais',async()=>{uploads.map=(await gm.upload(path.join(ROOT,'tests','fixtures','scene.png'),'image','image/png')).data.url;uploads.fg=(await gm.upload(path.join(ROOT,'tests','fixtures','scene.png'),'image','image/png')).data.url;uploads.audio=(await gm.upload(path.join(ROOT,'tests','fixtures','sound.wav'),'audio','audio/wav')).data.url});
  await check('Criar pasta de cenas',async()=>{ids.folder=(await gm.req(`/api/vtt/chronicles/${cid}/scene-folders`,{method:'POST',body:{name:'Sessões 1-5',position:1},expected:201})).data.id});
  await check('Criar cena VTT quadrada completa',async()=>{const r=await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Armazém no Porto',description:'Cena investigativa',imageUrl:uploads.map,foregroundUrl:uploads.fg,folderId:ids.folder,width:1600,height:1000,gridType:'square',gridSize:70,gridUnits:'m',gridDistance:1.5,darkness:.35,globalIllumination:true,fogEnabled:true,explorerEnabled:true,restrictMovement:true,weatherEffect:'rain',navVisible:true},expected:201});scene.porto=r.data.id;await gm.req(`/api/vtt/scenes/${scene.porto}/activate`,{method:'POST',body:{},expected:200})},{critical:true});
  await check('Bootstrap VTT carrega cena e permissões',async()=>{const r=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(r.data.canManage,false);assert.ok(r.data.scenes.some(s=>s.id===scene.porto));assert.equal(r.data.permissions.canRoll,true)});
  await check('Co-Mestre possui gestão VTT',async()=>{const r=await co.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(r.data.canManage,true)});
  await check('Criar NPC',async()=>{ids.npc=(await gm.req(`/api/chronicles/${cid}/npcs`,{method:'POST',body:{name:'Silas',type:'Vampiro',importance:'important',imageUrl:uploads.avatar,description:'Informante',defense:3,health:5,damage:2,pools:{persuasao:6}},expected:201})).data.id});
  await check('Criar token dos três jogadores + NPC',async()=>{obj.t1=(await gm.req(`/api/vtt/scenes/${scene.porto}/tokens`,{method:'POST',body:{characterId:chars.p1,ownerUserId:U.p1.id,name:'Helena',imageUrl:uploads.avatar,x:180,y:400,width:70,height:70,visionEnabled:true,visionRange:500,disposition:'friendly',bar1Value:3,bar1Max:5,status:['focused']},expected:201})).data.id;obj.t2=(await gm.req(`/api/vtt/scenes/${scene.porto}/tokens`,{method:'POST',body:{characterId:chars.p2,ownerUserId:U.p2.id,name:'Davi',x:260,y:400,width:70,height:70,visionEnabled:true,visionRange:450,disposition:'friendly'},expected:201})).data.id;obj.t3=(await gm.req(`/api/vtt/scenes/${scene.porto}/tokens`,{method:'POST',body:{characterId:chars.p3,ownerUserId:U.p3.id,name:'Lívia',x:340,y:400,width:70,height:70,visionEnabled:true,visionRange:420,disposition:'friendly'},expected:201})).data.id;obj.npcTok=(await gm.req(`/api/vtt/scenes/${scene.porto}/tokens`,{method:'POST',body:{npcId:ids.npc,name:'Silas',x:900,y:450,width:70,height:70,visionEnabled:false,disposition:'neutral'},expected:201})).data.id});
  await check('Criar tile under/over/GM e filtrar GM layer do jogador',async()=>{obj.tileUnder=(await gm.req(`/api/vtt/scenes/${scene.porto}/tiles`,{method:'POST',body:{name:'Mesa',imageUrl:uploads.map,x:600,y:400,width:200,height:120,layer:'under'},expected:201})).data.id;obj.tileOver=(await gm.req(`/api/vtt/scenes/${scene.porto}/tiles`,{method:'POST',body:{name:'Fumaça',imageUrl:uploads.map,x:700,y:300,width:250,height:180,layer:'over',opacity:.5},expected:201})).data.id;obj.tileGm=(await gm.req(`/api/vtt/scenes/${scene.porto}/tiles`,{method:'POST',body:{name:'Segredo',imageUrl:uploads.map,x:1000,y:200,width:100,height:100,layer:'gm'},expected:201})).data.id;const r=await p1.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});assert.ok(!r.data.objects.tiles.some(x=>x.id===obj.tileGm))});
  await check('Jogador cria desenho livre',async()=>{obj.drawP1=(await p1.req(`/api/vtt/scenes/${scene.porto}/drawings`,{method:'POST',body:{drawingType:'freehand',points:[{x:100,y:100},{x:140,y:120},{x:160,y:160}],stroke:'#fff',strokeWidth:3},expected:201})).data.id});
  await check('Mestre cria retângulo, elipse e texto',async()=>{for(const body of [{drawingType:'rect',x:400,y:100,width:100,height:80},{drawingType:'ellipse',x:520,y:100,width:120,height:80},{drawingType:'text',x:650,y:100,text:'Pista'}]) await gm.req(`/api/vtt/scenes/${scene.porto}/drawings`,{method:'POST',body,expected:201})});
  await check('Espectador não desenha',async()=>await spec.req(`/api/vtt/scenes/${scene.porto}/drawings`,{method:'POST',body:{drawingType:'rect',x:1,y:1,width:10,height:10},expected:403}));
  await check('Criar luz, som, nota e região',async()=>{obj.light=(await gm.req(`/api/vtt/scenes/${scene.porto}/lights`,{method:'POST',body:{name:'Poste',x:700,y:500,brightRadius:120,dimRadius:260,angle:270,color:'#ffdca0',intensity:1.2},expected:201})).data.id;obj.sound=(await gm.req(`/api/vtt/scenes/${scene.porto}/sounds`,{method:'POST',body:{name:'Chuva',url:uploads.audio,x:800,y:500,radius:700,volume:.65},expected:201})).data.id;obj.mapNote=(await gm.req(`/api/vtt/scenes/${scene.porto}/map-notes`,{method:'POST',body:{title:'Caixa marcada',content:'Símbolo estranho',x:1000,y:500,icon:'◆',visibility:'all'},expected:201})).data.id;obj.mapNoteSecret=(await gm.req(`/api/vtt/scenes/${scene.porto}/map-notes`,{method:'POST',body:{title:'Segredo',content:'Só Mestre',x:1100,y:500,visibility:'master'},expected:201})).data.id;obj.region=(await gm.req(`/api/vtt/scenes/${scene.porto}/regions`,{method:'POST',body:{name:'Área contaminada',x:1200,y:300,width:250,height:220,shape:'ellipse',behavior:{message:'Cheiro de sangue',effect:'warning'}},expected:201})).data.id;const r=await p1.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});assert.ok(r.data.objects.notes.some(x=>x.id===obj.mapNote));assert.ok(!r.data.objects.notes.some(x=>x.id===obj.mapNoteSecret))});
  await check('Ping e FX aparecem como pings temporários',async()=>{obj.ping=(await p1.req(`/api/vtt/scenes/${scene.porto}/pings`,{method:'POST',body:{x:500,y:500,pingType:'ping',label:'Aqui'},expected:201})).data.id;obj.fx=(await gm.req(`/api/vtt/scenes/${scene.porto}/pings`,{method:'POST',body:{x:600,y:500,pingType:'fx',label:'Sangue'},expected:201})).data.id;const r=await p2.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});assert.ok(r.data.pings.some(x=>x.id===obj.ping));assert.ok(r.data.pings.some(x=>x.id===obj.fx))});
  await check('Presença VTT registra cursor remoto',async()=>{await p1.req(`/api/vtt/chronicles/${cid}/presence`,{method:'POST',body:{sceneId:scene.porto,cursorX:321,cursorY:654},expected:200});const r=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});const m=r.data.members.find(x=>x.id===U.p1.id);assert.equal(m.cursor_x,321);assert.equal(m.cursor_y,654)});
  await check('Notas: master oculta, pública preparada e selecionada',async()=>{ids.noteMaster=(await gm.req(`/api/chronicles/${cid}/notes`,{method:'POST',body:{title:'Plano secreto',content:'Só mestre',visibility:'master',isRevealed:false},expected:201})).data.id;ids.noteAll=(await gm.req(`/api/chronicles/${cid}/notes`,{method:'POST',body:{title:'Fotografia',content:'Pista pública',visibility:'all',isRevealed:false},expected:201})).data.id;ids.noteSelected=(await gm.req(`/api/chronicles/${cid}/notes`,{method:'POST',body:{title:'Bilhete para Helena',content:'Você reconhece o símbolo',visibility:'selected',recipientIds:[U.p1.id],isRevealed:true},expected:201})).data.id;let a=await p1.req(`/api/chronicles/${cid}/notes`,{expected:200});let b=await p2.req(`/api/chronicles/${cid}/notes`,{expected:200});assert.ok(a.data.notes.some(n=>n.id===ids.noteSelected));assert.ok(!b.data.notes.some(n=>n.id===ids.noteSelected));assert.ok(!a.data.notes.some(n=>n.id===ids.noteAll));await gm.req(`/api/notes/${ids.noteAll}/reveal`,{method:'POST',body:{},expected:200});a=await p1.req(`/api/chronicles/${cid}/notes`,{expected:200});assert.ok(a.data.notes.some(n=>n.id===ids.noteAll))});
  await check('Jogador cria nota privada ao Mestre',async()=>{ids.playerNote=(await p1.req(`/api/chronicles/${cid}/notes`,{method:'POST',body:{title:'Desconfiança',content:'Acho que Silas mente',visibility:'all'},expected:201})).data.id;const a=await p2.req(`/api/chronicles/${cid}/notes`,{expected:200});const g=await gm.req(`/api/chronicles/${cid}/notes`,{expected:200});assert.ok(!a.data.notes.some(n=>n.id===ids.playerNote));assert.ok(g.data.notes.some(n=>n.id===ids.playerNote))});
  await check('Chat geral, notas e sussurro isolado',async()=>{await p1.req(`/api/chronicles/${cid}/messages`,{method:'POST',body:{channel:'general',content:'Eu examino a caixa.'},expected:201});await gm.req(`/api/chronicles/${cid}/messages`,{method:'POST',body:{channel:'notes',content:'Teste de percepção.'},expected:201});await p1.req(`/api/chronicles/${cid}/messages`,{method:'POST',body:{channel:'whisper',recipientId:U.gm.id,content:'Quero fazer isso escondido.'},expected:201});const a=await gm.req(`/api/chronicles/${cid}/messages`,{expected:200});const b=await p2.req(`/api/chronicles/${cid}/messages`,{expected:200});assert.ok(a.data.messages.some(m=>m.channel==='whisper'));assert.ok(!b.data.messages.some(m=>m.channel==='whisper'))});
  await check('Diário público e privado',async()=>{ids.diaryAll=(await gm.req(`/api/chronicles/${cid}/diary`,{method:'POST',body:{entryType:'session',title:'Sessão 2',content:'Investigação no porto',visibility:'all'},expected:201})).data.id;ids.diaryMaster=(await gm.req(`/api/chronicles/${cid}/diary`,{method:'POST',body:{entryType:'faction',title:'Segredo da Camarilla',content:'Plano',visibility:'master'},expected:201})).data.id;const r=await p1.req(`/api/chronicles/${cid}/diary`,{expected:200});assert.ok(r.data.items.some(x=>x.id===ids.diaryAll));assert.ok(!r.data.items.some(x=>x.id===ids.diaryMaster))});
  await check('Story temporada/episódio/ato/cena',async()=>{ids.season=(await gm.req(`/api/chronicles/${cid}/story`,{method:'POST',body:{nodeType:'season',title:'Temporada 1',position:1},expected:201})).data.id;ids.episode=(await gm.req(`/api/chronicles/${cid}/story`,{method:'POST',body:{nodeType:'episode',parentId:ids.season,title:'Porto de Sangue',position:1},expected:201})).data.id;ids.act=(await gm.req(`/api/chronicles/${cid}/story`,{method:'POST',body:{nodeType:'act',parentId:ids.episode,title:'Ato I',position:1},expected:201})).data.id;ids.storyScene=(await gm.req(`/api/chronicles/${cid}/story`,{method:'POST',body:{nodeType:'scene',parentId:ids.act,title:'O Armazém',position:1},expected:201})).data.id});
  await check('Timeline all/partial/master filtra segredo',async()=>{ids.timelineAll=(await gm.req(`/api/chronicles/${cid}/timeline`,{method:'POST',body:{title:'Desaparecimento',content:'Marco público',eventDate:'2026-08-28',visibility:'all'},expected:201})).data.id;ids.timelinePartial=(await gm.req(`/api/chronicles/${cid}/timeline`,{method:'POST',body:{title:'Boato',content:'Informação parcial',visibility:'partial'},expected:201})).data.id;ids.timelineMaster=(await gm.req(`/api/chronicles/${cid}/timeline`,{method:'POST',body:{title:'Verdade',content:'Segredo',visibility:'master'},expected:201})).data.id;const r=await p1.req(`/api/chronicles/${cid}/timeline`,{expected:200});assert.ok(r.data.items.some(x=>x.id===ids.timelinePartial));assert.ok(!r.data.items.some(x=>x.id===ids.timelineMaster))});
  await check('Mapa narrativo com marcador',async()=>{ids.map=(await gm.req(`/api/chronicles/${cid}/maps`,{method:'POST',body:{title:'Vitória',mapType:'narrative',imageUrl:uploads.map,gridEnabled:false,markers:[{x:20,y:30,label:'Porto'}]},expected:201})).data.id;await gm.req(`/api/maps/${ids.map}`,{method:'PATCH',body:{markers:[{x:20,y:30,label:'Porto'},{x:60,y:40,label:'Elysium'}]},expected:200});const r=await p1.req(`/api/chronicles/${cid}/maps`,{expected:200});assert.equal(JSON.parse(r.data.items.find(x=>x.id===ids.map).markers_json).length,2)});
  await check('Relógio narrativo criado e avança',async()=>{ids.clock=(await gm.req(`/api/chronicles/${cid}/clocks`,{method:'POST',body:{title:'Caçadores chegam',segments:6,consequence:'Ataque'},expected:201})).data.id;await gm.req(`/api/clocks/${ids.clock}`,{method:'PATCH',body:{progress:2},expected:200});const r=await p1.req(`/api/chronicles/${cid}/clocks`,{expected:200});assert.equal(r.data.items.find(x=>x.id===ids.clock).progress,2)});
});

await group(3,'Primeiro conflito: paredes, Fog, rolagens, pausa e combate',async()=>{
  await check('Parede completa e porta fechada',async()=>{obj.wallA=(await gm.req(`/api/vtt/scenes/${scene.porto}/walls`,{method:'POST',body:{x1:700,y1:0,x2:700,y2:350,wallType:'wall',blocksVision:true,blocksMovement:true,blocksSound:true},expected:201})).data.id;obj.door=(await gm.req(`/api/vtt/scenes/${scene.porto}/walls`,{method:'POST',body:{x1:700,y1:350,x2:700,y2:650,wallType:'door',doorState:'closed',blocksVision:true,blocksMovement:true,blocksSound:true},expected:201})).data.id;obj.wallB=(await gm.req(`/api/vtt/scenes/${scene.porto}/walls`,{method:'POST',body:{x1:700,y1:650,x2:700,y2:1000,wallType:'wall',blocksVision:true,blocksMovement:true,blocksSound:true},expected:201})).data.id});
  await check('Fog global revela área e persiste',async()=>{await gm.req(`/api/vtt/scenes/${scene.porto}/fog`,{method:'PUT',body:{scope:'global',revealed:[{x:0,y:0,w:450,h:500}]},expected:200});const r=await p1.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});assert.equal(r.data.fog.global.revealed.length,1)});
  await check('Explorer respeita parede',async()=>{const r=await p1.req(`/api/vtt/scenes/${scene.porto}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.t1},expected:200});assert.ok(Math.max(...r.data.exploredShape.points.map(p=>p.x))<=700.01)});
  await check('Jogador não altera Fog global',async()=>await p1.req(`/api/vtt/scenes/${scene.porto}/fog`,{method:'PUT',body:{scope:'global',revealed:[]},expected:403}));
  await check('Porta fechada bloqueia movimento',async()=>await p1.req(`/api/vtt/tokens/${obj.t1}`,{method:'PATCH',body:{x:850,y:400},expected:409}));
  await check('Jogador abre porta normal e atravessa',async()=>{await p1.req(`/api/vtt/walls/${obj.door}/toggle`,{method:'POST',body:{},expected:200});await p1.req(`/api/vtt/tokens/${obj.t1}`,{method:'PATCH',body:{x:850,y:400},expected:200})});
  await check('Porta trancada bloqueia jogador',async()=>{await gm.req(`/api/vtt/walls/${obj.door}`,{method:'PATCH',body:{doorState:'locked'},expected:200});await p1.req(`/api/vtt/walls/${obj.door}/toggle`,{method:'POST',body:{},expected:409});await gm.req(`/api/vtt/walls/${obj.door}`,{method:'PATCH',body:{doorState:'open'},expected:200})});
  await check('Combate detalhado criado',async()=>{ids.conflict=(await gm.req(`/api/chronicles/${cid}/conflicts`,{method:'POST',body:{title:'Emboscada',mode:'detailed',participants:[{name:'Helena',initiative:6},{name:'Silas',initiative:5}],notes:'Teste'},expected:201})).data.id;await gm.req(`/api/conflicts/${ids.conflict}`,{method:'PATCH',body:{round:2,notes:'Rodada 2'},expected:200});const r=await p1.req(`/api/chronicles/${cid}/conflicts`,{expected:200});assert.equal(r.data.conflicts.find(x=>x.id===ids.conflict).round,2)});
  await check('Solicitação de rolagem enviada ao jogador certo',async()=>{ids.rollReq=(await gm.req(`/api/chronicles/${cid}/roll-requests`,{method:'POST',body:{targetUserId:U.p1.id,characterId:chars.p1,attributeName:'destreza',skillName:'investigacao',difficulty:3,modifier:1,prompt:'Examinar a cena'},expected:201})).data.id;const r=await p1.req(`/api/chronicles/${cid}/roll-requests`,{expected:200});assert.ok(r.data.requests.some(x=>x.id===ids.rollReq));const other=await p2.req(`/api/chronicles/${cid}/roll-requests`,{expected:200});assert.ok(!other.data.requests.some(x=>x.id===ids.rollReq))});
  await check('Solicitação com personagem de outro jogador é rejeitada',async()=>await gm.req(`/api/chronicles/${cid}/roll-requests`,{method:'POST',body:{targetUserId:U.p1.id,characterId:chars.p2,attributeName:'destreza'},expected:400}));
  await check('Rolagem solicitada conclui request e usa Fome da ficha',async()=>{const r=await p1.req(`/api/chronicles/${cid}/rolls`,{method:'POST',body:{characterId:chars.p1,attributeName:'destreza',skillName:'investigacao',modifier:1,difficulty:3,requestId:ids.rollReq},expected:201});assert.equal(r.data.roll.hunger,2);const pending=await p1.req(`/api/chronicles/${cid}/roll-requests`,{expected:200});assert.ok(!pending.data.requests.some(x=>x.id===ids.rollReq))});
  await check('Rolagem VTT pública aparece para outros',async()=>{const r=await gm.req(`/api/vtt/chronicles/${cid}/rolls`,{method:'POST',body:{pool:8,hunger:3,attributeName:'forca',skillName:'briga',difficulty:3},expected:201});ids.publicRoll=r.data.roll.id;const p=await p1.req(`/api/vtt/chronicles/${cid}/rolls`,{expected:200});assert.ok(p.data.rolls.some(x=>x.id===ids.publicRoll))});
  await check('Rolagem secreta do Mestre é filtrada',async()=>{const r=await gm.req(`/api/vtt/chronicles/${cid}/rolls`,{method:'POST',body:{pool:7,hunger:2,secret:true,attributeName:'raciocinio',skillName:'ocultismo'},expected:201});ids.secretRoll=r.data.roll.id;const g=await gm.req(`/api/vtt/chronicles/${cid}/rolls`,{expected:200});const p=await p2.req(`/api/vtt/chronicles/${cid}/rolls`,{expected:200});assert.ok(g.data.rolls.some(x=>x.id===ids.secretRoll));assert.ok(!p.data.rolls.some(x=>x.id===ids.secretRoll))});
  await check('Jogador não pode tornar rolagem secreta',async()=>{const r=await p1.req(`/api/vtt/chronicles/${cid}/rolls`,{method:'POST',body:{characterId:chars.p1,pool:5,secret:true},expected:201});assert.equal(Boolean(r.data.roll.is_secret),false)});
  await check('Espectador não rola',async()=>await spec.req(`/api/vtt/chronicles/${cid}/rolls`,{method:'POST',body:{pool:5},expected:403}));
  await check('Pausa global bloqueia movimento do jogador e não do Mestre',async()=>{await gm.req(`/api/vtt/chronicles/${cid}/pause`,{method:'POST',body:{paused:true},expected:200});await p2.req(`/api/vtt/tokens/${obj.t2}`,{method:'PATCH',body:{x:300,y:500},expected:409});await gm.req(`/api/vtt/tokens/${obj.npcTok}`,{method:'PATCH',body:{x:950,y:450},expected:200});await gm.req(`/api/vtt/chronicles/${cid}/pause`,{method:'POST',body:{paused:false},expected:200})});
  await check('Borracha: jogador apaga próprio desenho, não objeto do Mestre',async()=>{await p1.req(`/api/vtt/drawings/${obj.drawP1}`,{method:'DELETE',expected:200});await p1.req(`/api/vtt/tokens/${obj.npcTok}`,{method:'DELETE',expected:403})});
});

await group(4,'Cena cinematográfica: mídia, evento, cutscene e transmissão',async()=>{
  await check('Upload MP4 real de cutscene',async()=>{uploads.video=(await gm.upload(path.join(ROOT,'tests','fixtures','cutscene.mp4'),'video','video/mp4')).data.url});
  await check('Criar e ativar mídia de áudio local',async()=>{ids.media=(await gm.req(`/api/chronicles/${cid}/media`,{method:'POST',body:{title:'Tensão',category:'Perigo',url:uploads.audio,mediaType:'audio'},expected:201})).data.id;await gm.req(`/api/media/${ids.media}/activate`,{method:'POST',body:{},expected:200});const live=await p1.req(`/api/chronicles/${cid}/live`,{expected:200});assert.equal(live.data.media.id,ids.media)});
  await check('Criar evento narrativo e ativar',async()=>{ids.event=(await gm.req(`/api/chronicles/${cid}/events`,{method:'POST',body:{eventType:'revelation',title:'O corpo se levanta',content:'A Besta desperta',payload:{fx:'blood'}},expected:201})).data.id;await gm.req(`/api/events/${ids.event}/activate`,{method:'POST',body:{},expected:200});const live=await p2.req(`/api/chronicles/${cid}/live`,{expected:200});assert.equal(live.data.event.id,ids.event)});
  await check('Criar cutscene local',async()=>{ids.cut=(await gm.req(`/api/chronicles/${cid}/cutscenes`,{method:'POST',body:{title:'Visão do Príncipe',videoUrl:uploads.video,steps:[]},expected:201})).data.id});
  await check('Lançar cutscene substitui estado ao vivo',async()=>{await gm.req(`/api/cutscenes/${ids.cut}/launch`,{method:'POST',body:{},expected:200});const live=await p1.req(`/api/chronicles/${cid}/live`,{expected:200});assert.equal(live.data.cutscene.id,ids.cut);assert.equal(live.data.cutscene.playbackState,'playing')});
  await new Promise(r=>setTimeout(r,250));
  await check('Pausar cutscene salva posição',async()=>{const r=await gm.req(`/api/cutscenes/${ids.cut}/pause`,{method:'POST',body:{},expected:200});assert.equal(r.data.state,'paused');assert.ok(r.data.position>=0)});
  await check('Retomar cutscene',async()=>{const r=await gm.req(`/api/cutscenes/${ids.cut}/resume`,{method:'POST',body:{},expected:200});assert.equal(r.data.state,'playing')});
  await check('Encerrar cutscene remove overlay do estado live',async()=>{await gm.req(`/api/cutscenes/${ids.cut}/end`,{method:'POST',body:{},expected:200});const live=await p1.req(`/api/chronicles/${cid}/live`,{expected:200});assert.equal(live.data.cutscene,null)});
  await check('Desativar mídia e evento',async()=>{await gm.req(`/api/media/${ids.media}/deactivate`,{method:'POST',body:{},expected:200});await gm.req(`/api/events/${ids.event}/deactivate`,{method:'POST',body:{},expected:200});const live=await p1.req(`/api/chronicles/${cid}/live`,{expected:200});assert.equal(live.data.media,null);assert.equal(live.data.event,null)});
  await check('Página de transmissão é servida',async()=>{const r=await fetch(BASE+`/pages/transmissao.html?id=${cid}`);assert.equal(r.status,200);const text=await r.text();assert.match(text,/transmiss/i)});
});

await group(5,'Labirinto: Fog avançada, portas secretas, iluminação e clima',async()=>{
  await check('Criar cena hex-row escura com cinzas',async()=>{const r=await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Catacumbas',imageUrl:uploads.map,width:2000,height:1200,gridType:'hex-row',gridSize:80,darkness:.85,globalIllumination:false,fogEnabled:true,explorerEnabled:true,restrictMovement:true,weatherEffect:'ash',navVisible:true},expected:201});scene.cat=r.data.id;await gm.req(`/api/vtt/scenes/${scene.cat}/activate`,{method:'POST',body:{},expected:200})});
  await check('Tokens recriados na nova cena',async()=>{obj.cat1=(await gm.req(`/api/vtt/scenes/${scene.cat}/tokens`,{method:'POST',body:{ownerUserId:U.p1.id,characterId:chars.p1,name:'Helena',x:150,y:500,width:70,height:70,visionEnabled:true,visionRange:1100},expected:201})).data.id;obj.cat2=(await gm.req(`/api/vtt/scenes/${scene.cat}/tokens`,{method:'POST',body:{ownerUserId:U.p2.id,characterId:chars.p2,name:'Davi',x:1600,y:500,width:70,height:70,visionEnabled:true,visionRange:800},expected:201})).data.id});
  await check('Barreira até bordas + porta secreta fechada',async()=>{await gm.req(`/api/vtt/scenes/${scene.cat}/walls`,{method:'POST',body:{x1:900,y1:0,x2:900,y2:400,wallType:'wall'},expected:201});obj.secret=(await gm.req(`/api/vtt/scenes/${scene.cat}/walls`,{method:'POST',body:{x1:900,y1:400,x2:900,y2:800,wallType:'secret',doorState:'closed'},expected:201})).data.id;await gm.req(`/api/vtt/scenes/${scene.cat}/walls`,{method:'POST',body:{x1:900,y1:800,x2:900,y2:1200,wallType:'wall'},expected:201})});
  await check('Porta secreta é mascarada para jogador',async()=>{const r=await p1.req(`/api/vtt/scenes/${scene.cat}`,{expected:200});const w=r.data.objects.walls.find(x=>x.id===obj.secret);assert.equal(w.wall_type,'wall');assert.equal(w.door_state,'closed')});
  await check('Jogador não manipula passagem secreta',async()=>await p1.req(`/api/vtt/walls/${obj.secret}/toggle`,{method:'POST',body:{},expected:403}));
  await check('Explorer não vaza por borda nem secreta',async()=>{const r=await p1.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.cat1},expected:200});assert.ok(Math.max(...r.data.exploredShape.points.map(p=>p.x))<=900.01)});
  await check('Mestre abre secreta e visão atravessa sem revelar tipo',async()=>{await gm.req(`/api/vtt/walls/${obj.secret}`,{method:'PATCH',body:{doorState:'open'},expected:200});const r=await p1.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.cat1},expected:200});assert.ok(Math.max(...r.data.exploredShape.points.map(p=>p.x))>1000);const view=await p1.req(`/api/vtt/scenes/${scene.cat}`,{expected:200});assert.equal(view.data.objects.walls.find(x=>x.id===obj.secret).wall_type,'wall')});
  await check('Token sem visão não grava Explorer',async()=>{await gm.req(`/api/vtt/tokens/${obj.cat1}`,{method:'PATCH',body:{visionEnabled:false},expected:200});await p1.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.cat1},expected:403});await gm.req(`/api/vtt/tokens/${obj.cat1}`,{method:'PATCH',body:{visionEnabled:true},expected:200})});
  await check('Explorer desligado bloqueia gravação',async()=>{await gm.req(`/api/vtt/scenes/${scene.cat}`,{method:'PATCH',body:{explorerEnabled:false},expected:200});await p1.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.cat1},expected:409});await gm.req(`/api/vtt/scenes/${scene.cat}`,{method:'PATCH',body:{explorerEnabled:true},expected:200})});
  await check('Reset global preserva Explorer e Limpar Explorer apaga',async()=>{await gm.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'global',revealed:[{x:0,y:0,w:300,h:300}]},expected:200});await p1.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.cat1},expected:200});await gm.req(`/api/vtt/scenes/${scene.cat}/fog`,{method:'PUT',body:{scope:'global',revealed:[]},expected:200});let r=await p1.req(`/api/vtt/scenes/${scene.cat}`,{expected:200});assert.ok(r.data.fog.user.explored.length>0);await gm.req(`/api/vtt/scenes/${scene.cat}/fog/explorer`,{method:'DELETE',expected:200});r=await p1.req(`/api/vtt/scenes/${scene.cat}`,{expected:200});assert.equal(r.data.fog.user.explored.length,0)});
  await check('Luzes ocultas filtradas do jogador',async()=>{obj.hiddenLight=(await gm.req(`/api/vtt/scenes/${scene.cat}/lights`,{method:'POST',body:{name:'Luz secreta',x:500,y:500,hidden:true},expected:201})).data.id;const r=await p1.req(`/api/vtt/scenes/${scene.cat}`,{expected:200});assert.ok(!r.data.objects.lights.some(x=>x.id===obj.hiddenLight))});
  await check('Cena mantém grid hex e clima',async()=>{const r=await p1.req(`/api/vtt/scenes/${scene.cat}`,{expected:200});assert.equal(r.data.scene.grid_type,'hex-row');assert.equal(r.data.scene.weather_effect,'ash');assert.equal(r.data.scene.global_illumination,false)});
});

await group(6,'Ferramentas de diretório: itens, tabelas, cartas, macros e compêndio',async()=>{
  await check('Criar item público com imagem e dados',async()=>{ids.item=(await gm.req(`/api/vtt/chronicles/${cid}/items`,{method:'POST',body:{name:'Chave de Bronze',itemType:'clue',description:'Abre o cofre',imageUrl:uploads.avatar,data:{weight:1},folder:'Pistas',visibility:'all'},expected:201})).data.id});
  await check('Criar item master-only e filtrar jogador',async()=>{ids.itemSecret=(await gm.req(`/api/vtt/chronicles/${cid}/items`,{method:'POST',body:{name:'Dossiê secreto',visibility:'master'},expected:201})).data.id;const r=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.ok(r.data.items.some(x=>x.id===ids.item));assert.ok(!r.data.items.some(x=>x.id===ids.itemSecret))});
  await check('Editar item',async()=>{await gm.req(`/api/vtt/items/${ids.item}`,{method:'PATCH',body:{description:'Abre o cofre do Elysium',data:{weight:2}},expected:200});const r=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(r.data.items.find(x=>x.id===ids.item).data.weight,2)});
  await check('Tabela rolável criada e jogador rola',async()=>{ids.table=(await gm.req(`/api/vtt/chronicles/${cid}/tables`,{method:'POST',body:{name:'Rumores',formula:'1d6',entries:[{min:1,max:3,text:'Nada'},{min:4,max:6,text:'Pista'}],folder:'Sessão'},expected:201})).data.id;const r=await p1.req(`/api/vtt/tables/${ids.table}/roll`,{method:'POST',body:{secret:false},expected:200});assert.ok(r.data.roll.total>=1&&r.data.roll.total<=6)});
  await check('Tabela secreta do Mestre não posta resultado público',async()=>{const before=(await p2.req(`/api/chronicles/${cid}/messages`,{expected:200})).data.messages.length;await gm.req(`/api/vtt/tables/${ids.table}/roll`,{method:'POST',body:{secret:true},expected:200});const after=(await p2.req(`/api/chronicles/${cid}/messages`,{expected:200})).data.messages.length;assert.equal(after,before)});
  await check('Baralho: criar, comprar até vazio, conflito 409, reset e shuffle',async()=>{ids.deck=(await gm.req(`/api/vtt/chronicles/${cid}/decks`,{method:'POST',body:{name:'Cartas de Destino',cards:[{name:'A'},{name:'B'},{name:'C'}]},expected:201})).data.id;for(let i=0;i<3;i++)await p1.req(`/api/vtt/decks/${ids.deck}/draw`,{method:'POST',body:{},expected:200});await p1.req(`/api/vtt/decks/${ids.deck}/draw`,{method:'POST',body:{},expected:409});await gm.req(`/api/vtt/decks/${ids.deck}/reset`,{method:'POST',body:{},expected:200});await gm.req(`/api/vtt/decks/${ids.deck}/shuffle`,{method:'POST',body:{},expected:200});const r=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(r.data.decks.find(x=>x.id===ids.deck).cards.length,3)});
  await check('Macro privada do jogador não aparece para outro',async()=>{ids.macroPrivate=(await p1.req(`/api/vtt/chronicles/${cid}/macros`,{method:'POST',body:{name:'Meu teste',command:'/roll 5',icon:'◆',slot:0,visibility:'private'},expected:201})).data.id;const r=await p2.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.ok(!r.data.macros.some(x=>x.id===ids.macroPrivate))});
  await check('Macro compartilhada aparece para todos',async()=>{ids.macroAll=(await gm.req(`/api/vtt/chronicles/${cid}/macros`,{method:'POST',body:{name:'Rouse',command:'/roll 1',slot:1,visibility:'all'},expected:201})).data.id;const r=await p3.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.ok(r.data.macros.some(x=>x.id===ids.macroAll))});
  await check('Jogador não edita macro de outro',async()=>await p2.req(`/api/vtt/macros/${ids.macroPrivate}`,{method:'PATCH',body:{name:'Hack'},expected:403}));
  await check('Dono pode editar macro compartilhada',async()=>{await gm.req(`/api/vtt/macros/${ids.macroAll}`,{method:'PATCH',body:{slot:2,name:'Rouse Check'},expected:200})});
  await check('Hotbar aceita macros em páginas 2–5',async()=>{ids.macroPage2=(await p1.req(`/api/vtt/chronicles/${cid}/macros`,{method:'POST',body:{name:'Página 2',command:'/say pagina2',slot:10,visibility:'private'},expected:201})).data.id;ids.macroPage5=(await p1.req(`/api/vtt/chronicles/${cid}/macros`,{method:'POST',body:{name:'Página 5',command:'/say pagina5',slot:49,visibility:'private'},expected:201})).data.id;const r=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(r.data.macros.find(x=>x.id===ids.macroPage2).slot,10);assert.equal(r.data.macros.find(x=>x.id===ids.macroPage5).slot,49)});
  await check('Hotbar limita slot acima de 49',async()=>{const id=(await p1.req(`/api/vtt/chronicles/${cid}/macros`,{method:'POST',body:{name:'Clamp',command:'/say clamp',slot:999,visibility:'private'},expected:201})).data.id;const r=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(r.data.macros.find(x=>x.id===id).slot,49)});
  await check('Compêndio, hotbar e comandos de UI existem no frontend',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');for(const token of ['renderCompendium','runMacro','hotbar','measureType','ruler','radius','cone','togglePlayerView','fitScene','zoomAt','showTutorial','export-chat','HOTBAR_PAGES','changeHotbarPage']) assert.ok(js.includes(token),`faltando ${token}`)});
});

await group(7,'Mudança de atos: múltiplas cenas, grids, navegação e GM-only',async()=>{
  await check('Criar cena hex-column',async()=>{scene.hexcol=(await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Cobertura',width:1200,height:900,gridType:'hex-column',navVisible:true},expected:201})).data.id});
  await check('Criar cena gridless',async()=>{scene.gridless=(await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Elysium Social',width:1400,height:900,gridType:'gridless',navVisible:true},expected:201})).data.id});
  await check('Criar cena GM-only invisível',async()=>{scene.gm=(await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Sala do Príncipe',width:1000,height:700,gmOnly:true,navVisible:false},expected:201})).data.id;const b=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.ok(!b.data.scenes.some(x=>x.id===scene.gm));await p1.req(`/api/vtt/scenes/${scene.gm}`,{expected:403})});
  await check('Ativar cena GM-only permite acesso por ser atual',async()=>{await gm.req(`/api/vtt/scenes/${scene.gm}/activate`,{method:'POST',body:{},expected:200});const b=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.ok(b.data.scenes.some(x=>x.id===scene.gm));const r=await p1.req(`/api/vtt/scenes/${scene.gm}`,{expected:200});assert.equal(r.data.scene.is_current,true)});
  await check('Editar cena troca grid, darkness e weather sem perder ID',async()=>{await gm.req(`/api/vtt/scenes/${scene.hexcol}`,{method:'PATCH',body:{gridType:'square',darkness:.4,weatherEffect:'snow',foregroundUrl:uploads.fg},expected:200});const r=await gm.req(`/api/vtt/scenes/${scene.hexcol}`,{expected:200});assert.equal(r.data.scene.grid_type,'square');assert.equal(r.data.scene.weather_effect,'snow')});
  await check('Pasta temporária pode ser removida sem apagar cenas',async()=>{ids.tempFolder=(await gm.req(`/api/vtt/chronicles/${cid}/scene-folders`,{method:'POST',body:{name:'Temp'},expected:201})).data.id;await gm.req(`/api/vtt/scenes/${scene.hexcol}`,{method:'PATCH',body:{folderId:ids.tempFolder},expected:200});await gm.req(`/api/vtt/scene-folders/${ids.tempFolder}`,{method:'DELETE',expected:200});const r=await gm.req(`/api/vtt/scenes/${scene.hexcol}`,{expected:200});assert.equal(r.data.scene.folder_id,null)});
  await check('Cena temporária pode ser criada e deletada com cascade',async()=>{const t=(await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Temp'},expected:201})).data.id;await gm.req(`/api/vtt/scenes/${t}/tokens`,{method:'POST',body:{name:'Temp Token'},expected:201});await gm.req(`/api/vtt/scenes/${t}`,{method:'DELETE',expected:200});await gm.req(`/api/vtt/scenes/${t}`,{expected:404})});
  await check('Ativação entre cenas mantém apenas uma atual',async()=>{await gm.req(`/api/vtt/scenes/${scene.gridless}/activate`,{method:'POST',body:{},expected:200});const b=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(b.data.scenes.filter(x=>x.is_current).length,1);assert.equal(b.data.scenes.find(x=>x.is_current).id,scene.gridless)});
});

await group(8,'Permissões reais: Co-Mestre, Jogadores, Espectador e Admin',async()=>{
  await check('Co-Mestre cria cena e objetos administrativos',async()=>{scene.co=(await co.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Cena do Co-Mestre',width:900,height:700},expected:201})).data.id;await co.req(`/api/vtt/scenes/${scene.co}/walls`,{method:'POST',body:{x1:100,y1:100,x2:300,y2:100},expected:201})});
  await check('Jogador não cria token/tile/wall/luz/som/nota/região',async()=>{for(const type of ['tokens','tiles','walls','lights','sounds','map-notes','regions']) await p1.req(`/api/vtt/scenes/${scene.co}/${type}`,{method:'POST',body:{name:'x',x1:0,y1:0,x2:10,y2:10},expected:403})});
  await check('Espectador não movimenta token',async()=>{const tok=(await gm.req(`/api/vtt/scenes/${scene.co}/tokens`,{method:'POST',body:{name:'Spectator target',ownerUserId:U.spec.id,x:100,y:100},expected:201})).data.id;await spec.req(`/api/vtt/tokens/${tok}`,{method:'PATCH',body:{x:200,y:200},expected:403})});
  await check('Jogador não apaga ping de outro',async()=>{const ping=(await p2.req(`/api/vtt/scenes/${scene.co}/pings`,{method:'POST',body:{x:10,y:10},expected:201})).data.id;await p1.req(`/api/vtt/pings/${ping}`,{method:'DELETE',expected:403});await p2.req(`/api/vtt/pings/${ping}`,{method:'DELETE',expected:200})});
  await check('Mestre limpa marcações sem apagar tokens/tiles',async()=>{const dr=(await p1.req(`/api/vtt/scenes/${scene.co}/drawings`,{method:'POST',body:{drawingType:'rect',x:20,y:20,width:50,height:50},expected:201})).data.id;const tok=(await gm.req(`/api/vtt/scenes/${scene.co}/tokens`,{method:'POST',body:{name:'Preservado'},expected:201})).data.id;const tile=(await gm.req(`/api/vtt/scenes/${scene.co}/tiles`,{method:'POST',body:{name:'Preservado',imageUrl:uploads.map},expected:201})).data.id;await gm.req(`/api/vtt/scenes/${scene.co}/clear-markings`,{method:'POST',body:{},expected:200});const r=await gm.req(`/api/vtt/scenes/${scene.co}`,{expected:200});assert.ok(r.data.objects.tokens.some(x=>x.id===tok));assert.ok(r.data.objects.tiles.some(x=>x.id===tile));assert.ok(!r.data.objects.drawings.some(x=>x.id===dr))});
  await check('Co-Mestre pode pausar e retomar',async()=>{await co.req(`/api/vtt/chronicles/${cid}/pause`,{method:'POST',body:{paused:true},expected:200});let b=await p1.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(b.data.world.paused,true);await co.req(`/api/vtt/chronicles/${cid}/pause`,{method:'POST',body:{paused:false},expected:200})});
  await check('Promover jogador a co-master e voltar a player',async()=>{await gm.req(`/api/chronicles/${cid}/members/${U.p3.id}`,{method:'PATCH',body:{role:'co-master'},expected:200});let b=await p3.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(b.data.canManage,true);await gm.req(`/api/chronicles/${cid}/members/${U.p3.id}`,{method:'PATCH',body:{role:'player'},expected:200});b=await p3.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(b.data.canManage,false)});
  await check('Dono não pode ter papel alterado',async()=>await gm.req(`/api/chronicles/${cid}/members/${U.gm.id}`,{method:'PATCH',body:{role:'player'},expected:400}));
  await check('Admin overview lista campanha e usuários',async()=>{const r=await gm.req('/api/admin/overview',{expected:200});assert.ok(r.data.stats.users>=7);assert.ok(r.data.chronicles.some(x=>x.id===cid))});
  await check('Não-admin não acessa painel Admin',async()=>await p1.req('/api/admin/overview',{expected:403}));
});

await group(9,'Sessão longa: carga, concorrência, histórico, cursores e estabilidade',async()=>{
  await check('Ativar cena de carga',async()=>await gm.req(`/api/vtt/scenes/${scene.porto}/activate`,{method:'POST',body:{},expected:200}));
  await check('50 mensagens concorrentes sem perda',async()=>{const calls=[];for(let i=0;i<50;i++) calls.push((i%2?p1:p2).req(`/api/chronicles/${cid}/messages`,{method:'POST',body:{channel:'general',content:`Mensagem carga ${i}`},expected:201}));await Promise.all(calls);const r=await gm.req(`/api/chronicles/${cid}/messages`,{expected:200});assert.ok(r.data.messages.filter(m=>m.content.startsWith('Mensagem carga')).length>=50)});
  await check('30 pings/FX concorrentes',async()=>{const calls=[];for(let i=0;i<30;i++)calls.push((i%3===0?gm:p1).req(`/api/vtt/scenes/${scene.porto}/pings`,{method:'POST',body:{x:100+i*10,y:200+i,pingType:i%3===0?'fx':'ping'},expected:201}));await Promise.all(calls);const r=await gm.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});assert.ok(r.data.pings.length<=30)});
  await check('25 rolagens concorrentes de jogadores',async()=>{const calls=[];for(let i=0;i<25;i++){const cl=[p1,p2,p3][i%3];const ch=[chars.p1,chars.p2,chars.p3][i%3];calls.push(cl.req(`/api/vtt/chronicles/${cid}/rolls`,{method:'POST',body:{characterId:ch,pool:6,hunger:2,difficulty:3},expected:201}));}await Promise.all(calls);const r=await gm.req(`/api/vtt/chronicles/${cid}/rolls`,{expected:200});assert.ok(r.data.rolls.length>=25)});
  await check('Explorer concorrente mantém isolamento',async()=>{await gm.req(`/api/vtt/scenes/${scene.porto}`,{method:'PATCH',body:{explorerEnabled:true,fogEnabled:true},expected:200});const calls=[];for(let i=0;i<15;i++)calls.push(p2.req(`/api/vtt/scenes/${scene.porto}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.t2},expected:200}));for(let i=0;i<17;i++)calls.push(p3.req(`/api/vtt/scenes/${scene.porto}/fog`,{method:'PUT',body:{scope:'user',tokenId:obj.t3},expected:200}));await Promise.all(calls);const a=await p2.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});const b=await p3.req(`/api/vtt/scenes/${scene.porto}`,{expected:200});assert.notDeepEqual(a.data.fog.user.explored,b.data.fog.user.explored)});
  await check('100 atualizações de presença/cursor não quebram bootstrap',async()=>{const calls=[];for(let i=0;i<100;i++){const cl=[p1,p2,p3,co][i%4];calls.push(cl.req(`/api/vtt/chronicles/${cid}/presence`,{method:'POST',body:{sceneId:scene.porto,cursorX:i*3,cursorY:i*2},expected:200}));}await Promise.all(calls);const b=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(b.data.members.length,6)});
  await check('Bootstrap em estado carregado responde e contém diretórios',async()=>{const t=Date.now();const b=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});const ms=Date.now()-t;assert.ok(Array.isArray(b.data.items)&&Array.isArray(b.data.tables)&&Array.isArray(b.data.decks)&&Array.isArray(b.data.macros));assert.ok(ms<3000,`bootstrap ${ms}ms`)});
  await check('Chat incremental after funciona',async()=>{const all=await p1.req(`/api/chronicles/${cid}/messages`,{expected:200});const last=all.data.messages.at(-1)?.id||0;await p2.req(`/api/chronicles/${cid}/messages`,{method:'POST',body:{content:'incremental-final'},expected:201});const inc=await p1.req(`/api/chronicles/${cid}/messages?after=${last}`,{expected:200});assert.equal(inc.data.messages.length,1);assert.equal(inc.data.messages[0].content,'incremental-final')});
});

await group(10,'Finale: progressão, encerramento, reinício e integridade de campanha',async()=>{
  await check('Atualizar recursos finais das fichas',async()=>{await gm.req(`/api/characters/${chars.p1}`,{method:'PATCH',body:{hunger:4,humanity:6,stains:2,healthCurrent:1,willpowerCurrent:2},expected:200});await gm.req(`/api/characters/${chars.p2}`,{method:'PATCH',body:{hunger:1,humanity:7,healthCurrent:2},expected:200});await gm.req(`/api/characters/${chars.p3}`,{method:'PATCH',body:{hunger:3,humanity:8,willpowerCurrent:1},expected:200})});
  await check('XP final para todos',async()=>{for(const ch of Object.values(chars)) await gm.req(`/api/characters/${ch}/xp`,{method:'POST',body:{amount:5,reason:'Final da campanha'},expected:200})});
  await check('Relógio completa e conflito encerra',async()=>{await gm.req(`/api/clocks/${ids.clock}`,{method:'PATCH',body:{progress:6},expected:200});await gm.req(`/api/conflicts/${ids.conflict}`,{method:'PATCH',body:{round:4,status:'finished',notes:'Conflito encerrado'},expected:200})});
  await check('Recap final no Diário e Timeline',async()=>{ids.recap=(await gm.req(`/api/chronicles/${cid}/diary`,{method:'POST',body:{entryType:'session',title:'Sessão 10 — Finale',content:'A campanha terminou.',visibility:'all',occurredAt:'2026-08-28'},expected:201})).data.id;await gm.req(`/api/chronicles/${cid}/timeline`,{method:'POST',body:{title:'Fim da Crônica',content:'Os personagens sobrevivem.',visibility:'all'},expected:201})});
  await check('Cutscene final lança e encerra',async()=>{await gm.req(`/api/cutscenes/${ids.cut}/launch`,{method:'POST',body:{},expected:200});let live=await p3.req(`/api/chronicles/${cid}/live`,{expected:200});assert.ok(live.data.cutscene);await gm.req(`/api/cutscenes/${ids.cut}/end`,{method:'POST',body:{},expected:200})});
  await check('Crônica marcada como encerrada',async()=>{await gm.req(`/api/chronicles/${cid}`,{method:'PATCH',body:{status:'finished'},expected:200});const r=await p1.req(`/api/chronicles/${cid}`,{expected:200});assert.equal(r.data.chronicle.status,'finished')});
  await check('Logout invalida sessão e login restaura',async()=>{await p1.req('/api/logout',{method:'POST',body:{},expected:200});await p1.req('/api/me',{expected:401});await p1.req('/api/login',{method:'POST',body:{email:'alice@campanha.test',password:'senha1234'},expected:200});await p1.req('/api/me',{expected:200})});
  await check('Estado antes do restart está completo',async()=>{const b=await gm.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.ok(b.data.scenes.length>=5);assert.ok(b.data.characters.length===3);assert.ok(b.data.rolls.length>=25)});
  await check('Reiniciar servidor preserva banco e uploads',async()=>{await stopServer();await startServer();const g2=client('GM-RELOGIN');await g2.req('/api/login',{method:'POST',body:{email:'gm@campanha.test',password:'senha1234'},expected:200});const c=await g2.req(`/api/chronicles/${cid}`,{expected:200});assert.equal(c.data.chronicle.status,'finished');const b=await g2.req(`/api/vtt/chronicles/${cid}/bootstrap`,{expected:200});assert.equal(b.data.characters.length,3);const file=await fetch(BASE+uploads.video);assert.equal(file.status,200);assert.match(file.headers.get('content-type')||'',/video\/mp4/)});
  await check('Jogadores relogam após restart e veem histórico',async()=>{const a=client('A-RELOGIN');await a.req('/api/login',{method:'POST',body:{email:'alice@campanha.test',password:'senha1234'},expected:200});const d=await a.req(`/api/chronicles/${cid}/diary`,{expected:200});assert.ok(d.data.items.some(x=>x.id===ids.recap));const rr=await a.req(`/api/vtt/chronicles/${cid}/rolls`,{expected:200});assert.ok(rr.data.rolls.length>0)});
  await check('SQLite integrity_check e foreign_key_check limpos',async()=>{const db=new DatabaseSync(path.join(ROOT,'data','elysium.db'));const integrity=db.prepare('PRAGMA integrity_check').get();assert.equal(integrity.integrity_check,'ok');const fk=db.prepare('PRAGMA foreign_key_check').all();assert.equal(fk.length,0);db.close()});
  await check('Crescimento de dados da campanha é coerente',async()=>{const db=new DatabaseSync(path.join(ROOT,'data','elysium.db'));const counts={users:db.prepare('SELECT COUNT(*) n FROM users').get().n,scenes:db.prepare('SELECT COUNT(*) n FROM scenes WHERE chronicle_id=?').get(cid).n,rolls:db.prepare('SELECT COUNT(*) n FROM rolls WHERE chronicle_id=?').get(cid).n,messages:db.prepare('SELECT COUNT(*) n FROM messages WHERE chronicle_id=?').get(cid).n};db.close();assert.equal(counts.users,7);assert.ok(counts.scenes>=5);assert.ok(counts.rolls>=25);assert.ok(counts.messages>=50)});
  await check('Cascade de exclusão em Crônica descartável',async()=>{const z=client('Z');await z.req('/api/login',{method:'POST',body:{email:'gm@campanha.test',password:'senha1234'},expected:200});const c=(await z.req('/api/chronicles',{method:'POST',body:{name:'Descartável'},expected:201})).data.chronicle.id;const s=(await z.req(`/api/vtt/chronicles/${c}/scenes`,{method:'POST',body:{title:'Tmp'},expected:201})).data.id;await z.req(`/api/vtt/scenes/${s}/tokens`,{method:'POST',body:{name:'Tmp'},expected:201});await z.req(`/api/chronicles/${c}`,{method:'DELETE',expected:200});const db=new DatabaseSync(path.join(ROOT,'data','elysium.db'));assert.equal(db.prepare('SELECT COUNT(*) n FROM scenes WHERE chronicle_id=?').get(c).n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM vtt_tokens WHERE chronicle_id=?').get(c).n,0);db.close()});
});

// Auditoria estática das ferramentas de interface que são puramente client-side.
currentSession=10;
await check('TODAS as 15 ferramentas da barra existem no HTML',async()=>{const html=await readFile(path.join(ROOT,'public/pages/vtt.html'),'utf8');const tools=['select','pan','measure','ping','draw','erase','token','tile','wall','light','sound','note','region','fog','fx'];for(const t of tools)assert.match(html,new RegExp(`data-tool=["']${t}["']`),`tool ${t}`)});
await check('Todos os diretórios principais existem',async()=>{const html=await readFile(path.join(ROOT,'public/pages/vtt.html'),'utf8');for(const id of ['chat-log','combat-list','scene-directory','actor-directory','item-directory','journal-directory','table-directory','deck-directory','media-directory','cutscene-directory','compendium-directory','settings-pane','macro-hotbar'])assert.ok(html.includes(`id="${id}"`),id)});
await check('Tutorial cobre cenas, navegação, desenho, Fog, rolagem e Cutscene',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');for(const term of ['Cenas','Navegação','Lápis e Borracha','Fog of War','Rolagens V5','Cutscenes','Chat e diretórios','Atalhos'])assert.ok(js.includes(term),term)});
await check('Ferramenta medir implementa régua, raio e cone',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');for(const term of ['ruler','radius','cone'])assert.ok(js.includes(term))});
await check('Setas da hotbar têm handlers e paginação real',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');assert.ok(js.includes('hotbar-prev'));assert.ok(js.includes('hotbar-next'));assert.ok(js.includes('changeHotbarPage(-1)'));assert.ok(js.includes('changeHotbarPage(1)'));assert.ok(js.includes('state.hotbarPage*10'))});
await check('Controles de zoom, fit, Player View e sidebar têm handlers',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');for(const term of ['#zoom-in','#zoom-out','#zoom-fit','#player-view','#toggle-sidebar'])assert.ok(js.includes(term),term)});
await check('Exportação de chat possui implementação',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');assert.ok(js.includes('export-chat'));assert.ok(js.includes('new Blob'));assert.ok(js.includes('URL.createObjectURL'));assert.ok(js.includes('a.download'))});
await check('Dados visuais usam d10 e overlay central',async()=>{const html=await readFile(path.join(ROOT,'public/pages/vtt.html'),'utf8');const css=await readFile(path.join(ROOT,'public/css/vtt.css'),'utf8');const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');assert.ok(html.includes('dice-overlay'));assert.ok(js.includes('animateDice'));assert.ok(css.includes('die-d10')||css.includes('dice-d10')||css.includes('d10'))});
await check('Nenhum input URL nativo na interface VTT',async()=>{const html=await readFile(path.join(ROOT,'public/pages/vtt.html'),'utf8');assert.ok(!/type=["']url["']/i.test(html))});
await check('Uploads locais existem para cena, tile, token, item e cutscene',async()=>{const js=await readFile(path.join(ROOT,'public/js/vtt.js'),'utf8');for(const term of ['uploadFile','videoFile','imageFile'])assert.ok(js.includes(term),term)});
await check('Modo transmissão sincroniza cutscene e rolagem',async()=>{const js=await readFile(path.join(ROOT,'public/js/transmissao.js'),'utf8');assert.ok(/cutscene/i.test(js));assert.ok(/recentRoll|roll/i.test(js))});

await stopServer();

const failed=results.filter(x=>!x.ok);
const summary={version:'1.0.0',campaign:'10 sessions',passed:results.length-failed.length,total:results.length,failed:failed.length,failedTests:failed.map(x=>({session:x.session,name:x.name,detail:x.detail?.split('\n')[0]})),sessions};
await writeFile(path.join(ROOT,'docs','test-results','campaign-10-sessions.json'),JSON.stringify({summary,results},null,2));
console.log('\nCAMPAIGN_SUMMARY',JSON.stringify(summary,null,2));
if(failed.length) process.exitCode=1;
