import assert from 'node:assert/strict';
const base=process.env.BASE_URL||'http://127.0.0.1:3101';
const results=[];
function record(name,ok,detail=''){results.push({name,ok,detail});if(!ok)console.error('FAIL',name,detail)}
async function check(name,fn){try{await fn();record(name,true)}catch(e){record(name,false,e.stack||e.message)}}
function client(){let cookie='';return {async req(path,{method='GET',body,expected}={}){const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});const sc=res.headers.get('set-cookie');if(sc)cookie=sc.split(';')[0];const data=await res.json().catch(()=>({}));if(expected!==undefined)assert.equal(res.status,expected,`${method} ${path}: ${res.status} ${JSON.stringify(data)}`);return {status:res.status,data};}}}
const gm=client(),p1=client(),p2=client();
let gmUser,p1User,p2User,cid,sceneId,token1,token2,secretId,normalDoorId;

await check('Servidor responde',async()=>{const r=await fetch(base+'/api/system/network');assert.equal(r.status,200)});
await check('Cadastro Mestre',async()=>{({data:{user:gmUser}}=await gm.req('/api/register',{method:'POST',body:{name:'Mestre Fog',email:'gm-fog@test.local',password:'senha1234'},expected:201}))});
await check('Cadastro Jogador 1',async()=>{({data:{user:p1User}}=await p1.req('/api/register',{method:'POST',body:{name:'Jogador Fog 1',email:'p1-fog@test.local',password:'senha1234'},expected:201}))});
await check('Cadastro Jogador 2',async()=>{({data:{user:p2User}}=await p2.req('/api/register',{method:'POST',body:{name:'Jogador Fog 2',email:'p2-fog@test.local',password:'senha1234'},expected:201}))});
await check('Criação da Crônica',async()=>{const r=await gm.req('/api/chronicles',{method:'POST',body:{name:'Auditoria Fog'},expected:201});cid=r.data.chronicle.id;assert.ok(cid)});
for(const [label,cl] of [['Jogador 1',p1],['Jogador 2',p2]])await check(`Convite e entrada ${label}`,async()=>{const inv=await gm.req(`/api/chronicles/${cid}/invitations`,{method:'POST',body:{role:'player'},expected:201});await cl.req('/api/invitations/join',{method:'POST',body:{code:inv.data.code},expected:200})});
await check('Cena com Fog + Explorer criada',async()=>{const r=await gm.req(`/api/vtt/chronicles/${cid}/scenes`,{method:'POST',body:{title:'Fog Lab',width:1000,height:800,gridType:'gridless',fogEnabled:true,explorerEnabled:true,restrictMovement:true,globalIllumination:true},expected:201});sceneId=r.data.id;await gm.req(`/api/vtt/scenes/${sceneId}/activate`,{method:'POST',body:{},expected:200})});
await check('Tokens separados por proprietário',async()=>{let r=await gm.req(`/api/vtt/scenes/${sceneId}/tokens`,{method:'POST',body:{name:'P1',ownerUserId:p1User.id,x:100,y:100,width:50,height:50,visionEnabled:true,visionRange:400},expected:201});token1=r.data.id;r=await gm.req(`/api/vtt/scenes/${sceneId}/tokens`,{method:'POST',body:{name:'P2',ownerUserId:p2User.id,x:100,y:500,width:50,height:50,visionEnabled:true,visionRange:250},expected:201});token2=r.data.id});
await check('Porta secreta fechada criada',async()=>{const r=await gm.req(`/api/vtt/scenes/${sceneId}/walls`,{method:'POST',body:{x1:300,y1:-1000,x2:300,y2:2000,wallType:'secret',doorState:'closed',blocksVision:true,blocksMovement:true},expected:201});secretId=r.data.id});

await check('Jogador recebe bloqueador secreto sem revelar que é secreto',async()=>{const r=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});const w=r.data.objects.walls.find(x=>x.id===secretId);assert.ok(w,'bloqueador de visão ausente');assert.equal(w.wall_type,'wall');assert.equal(w.door_state,'closed');assert.equal(w.blocks_vision,1);assert.equal('secret_masked' in w,false)});
await check('Explorer do jogador é calculado pelo servidor',async()=>{const r=await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});assert.equal(r.data.exploredCount,1);assert.equal(r.data.exploredShape.type,'polygon')});
await check('Explorer respeita parede/porta secreta fechada',async()=>{const r=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});const pts=r.data.fog.user.explored.at(-1).points;assert.ok(Math.max(...pts.map(p=>p.x))<=300.01,`maxX=${Math.max(...pts.map(p=>p.x))}`)});
await check('Explorer persiste após novo GET',async()=>{const a=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});const b=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.deepEqual(a.data.fog.user.explored,b.data.fog.user.explored)});
await check('Fog individual não vaza para outro jogador',async()=>{const r=await p2.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.equal(r.data.fog.user.explored.length,0)});
await check('Jogador não pode forjar Explorer enviando retângulo arbitrário',async()=>{await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',explored:[{x:0,y:0,w:1000,h:800}]},expected:403})});
await check('Jogador não pode explorar com token de outro jogador',async()=>{await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token2},expected:403})});
await check('Jogador não altera Fog global',async()=>{await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'global',revealed:[{x:0,y:0,w:100,h:100}]},expected:403})});

await check('Abrir porta secreta libera visão sem revelar handle secreto',async()=>{await gm.req(`/api/vtt/walls/${secretId}`,{method:'PATCH',body:{doorState:'open'},expected:200});const scene=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});const w=scene.data.objects.walls.find(x=>x.id===secretId);assert.equal(w.wall_type,'wall');assert.equal(w.door_state,'closed');assert.equal(w.blocks_vision,0);const r=await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});const pts=r.data.exploredShape.points;assert.ok(Math.max(...pts.map(p=>p.x))>500)});
await check('Fechar novamente porta secreta volta a cortar visão',async()=>{await gm.req(`/api/vtt/walls/${secretId}`,{method:'PATCH',body:{doorState:'closed'},expected:200});const r=await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});assert.ok(Math.max(...r.data.exploredShape.points.map(p=>p.x))<=300.01)});
await check('blocksVision=false libera visão mesmo com passagem fechada',async()=>{await gm.req(`/api/vtt/walls/${secretId}`,{method:'PATCH',body:{blocksVision:false,doorState:'closed'},expected:200});const r=await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});assert.ok(Math.max(...r.data.exploredShape.points.map(p=>p.x))>500);await gm.req(`/api/vtt/walls/${secretId}`,{method:'PATCH',body:{blocksVision:true},expected:200})});

await check('Porta normal fechada corta visão',async()=>{await gm.req(`/api/vtt/walls/${secretId}`,{method:'DELETE',expected:200});const r=await gm.req(`/api/vtt/scenes/${sceneId}/walls`,{method:'POST',body:{x1:300,y1:-1000,x2:300,y2:2000,wallType:'door',doorState:'closed',blocksVision:true,blocksMovement:true},expected:201});normalDoorId=r.data.id;const e=await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});assert.ok(Math.max(...e.data.exploredShape.points.map(p=>p.x))<=300.01)});
await check('Jogador pode abrir porta normal e visão é liberada',async()=>{await p1.req(`/api/vtt/walls/${normalDoorId}/toggle`,{method:'POST',body:{},expected:200});const e=await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});assert.ok(Math.max(...e.data.exploredShape.points.map(p=>p.x))>500)});
await check('Porta trancada não pode ser aberta por jogador',async()=>{await gm.req(`/api/vtt/walls/${normalDoorId}`,{method:'PATCH',body:{doorState:'locked'},expected:200});await p1.req(`/api/vtt/walls/${normalDoorId}/toggle`,{method:'POST',body:{},expected:409})});

await check('Visão desativada impede Explorer',async()=>{await gm.req(`/api/vtt/tokens/${token1}`,{method:'PATCH',body:{visionEnabled:false},expected:200});await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:403});await gm.req(`/api/vtt/tokens/${token1}`,{method:'PATCH',body:{visionEnabled:true},expected:200})});
await check('Token oculto impede Explorer do jogador',async()=>{await gm.req(`/api/vtt/tokens/${token1}`,{method:'PATCH',body:{hidden:true},expected:200});await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:403});await gm.req(`/api/vtt/tokens/${token1}`,{method:'PATCH',body:{hidden:false},expected:200})});
await check('Explorer desativado rejeita gravação',async()=>{await gm.req(`/api/vtt/scenes/${sceneId}`,{method:'PATCH',body:{explorerEnabled:false},expected:200});await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:409});await gm.req(`/api/vtt/scenes/${sceneId}`,{method:'PATCH',body:{explorerEnabled:true},expected:200})});

await check('Fog global do Mestre é persistido',async()=>{await gm.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'global',revealed:[{x:20,y:30,w:200,h:100}]},expected:200});const r=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.deepEqual(r.data.fog.global.revealed,[{x:20,y:30,w:200,h:100}])});
await check('Fog global é recortado aos limites da cena no servidor',async()=>{const r=await gm.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'global',revealed:[{x:-50,y:-50,w:1200,h:1000}]},expected:200});assert.deepEqual(r.data.revealed,[{x:0,y:0,w:1000,h:800}])});
await check('Shapes inválidos de Fog global são descartados',async()=>{const r=await gm.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'global',revealed:[{x:10,y:10,w:-2,h:5},{foo:'bar'},{x:5,y:5,w:10,h:10}]},expected:200});assert.deepEqual(r.data.revealed,[{x:5,y:5,w:10,h:10}])});
await check('Fog global limita fragmentação a 500 retângulos',async()=>{const many=Array.from({length:600},(_,i)=>({x:i%1000,y:(i*3)%800,w:2,h:2}));const r=await gm.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'global',revealed:many},expected:200});assert.equal(r.data.revealed.length,500)});
await check('Reset do Fog global persiste vazio',async()=>{await gm.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'global',revealed:[]},expected:200});const r=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.equal(r.data.fog.global.revealed.length,0)});

await check('Histórico do Explorer é limitado a 100 visões',async()=>{await gm.req(`/api/vtt/walls/${normalDoorId}`,{method:'DELETE',expected:200});for(let i=0;i<105;i++)await p1.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token1},expected:200});const r=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.equal(r.data.fog.user.explored.length,100)});
await check('Jogador 2 cria Explorer independente com seu token',async()=>{const r=await p2.req(`/api/vtt/scenes/${sceneId}/fog`,{method:'PUT',body:{scope:'user',tokenId:token2},expected:200});assert.equal(r.data.exploredCount,1);const p1s=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});const p2s=await p2.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.equal(p1s.data.fog.user.explored.length,100);assert.equal(p2s.data.fog.user.explored.length,1)});
await check('Jogador não pode limpar Explorer da mesa',async()=>{await p1.req(`/api/vtt/scenes/${sceneId}/fog/explorer`,{method:'DELETE',expected:403})});
await check('Mestre limpa Explorer de todos os jogadores',async()=>{const r=await gm.req(`/api/vtt/scenes/${sceneId}/fog/explorer`,{method:'DELETE',expected:200});assert.ok(r.data.cleared>=2);const a=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});const b=await p2.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.equal(a.data.fog.user.explored.length,0);assert.equal(b.data.fog.user.explored.length,0)});
await check('Desativar Fog mantém flag sincronizada',async()=>{await gm.req(`/api/vtt/scenes/${sceneId}`,{method:'PATCH',body:{fogEnabled:false},expected:200});const r=await p1.req(`/api/vtt/scenes/${sceneId}`,{expected:200});assert.equal(r.data.scene.fog_enabled,false);await gm.req(`/api/vtt/scenes/${sceneId}`,{method:'PATCH',body:{fogEnabled:true},expected:200})});

const failed=results.filter(x=>!x.ok);console.log(JSON.stringify({passed:results.length-failed.length,total:results.length,results},null,2));if(failed.length)process.exit(1);
